[package]
name = "tui-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
tui = "0.19.0"
test_macro = { path = "../test_macro" }
