[package]
name = "web_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.14", features = ["blocking"] }
error-chain = "0.12.4"
scraper = "0.14.0"
rand = "0.8.5"
