[package]
name = "huo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro_test = { path = "../macro_test" }
macro_test_derive = { path = "../macro_test/macro_test_derive" }
