[package]
name = "keycloak-client"
version = "0.1.0"
edition = "2021"

[dependencies]
keycloak = "24.0.301"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync"] }
reqwest = "0.12.4"
