[package]
name = "async_server"
version = "0.1.0"
edition = "2024"

[dependencies]
async_runtime = { path = "../async_runtime" }
data_layer = { path = "../data_layer" }

[profile.release]
opt-level = 'z'