[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.2.4"
crossbeam-channel = "0.5.6"
anyhow = "1.0.66"
log = "0.4.17"
env_logger = "0.10.0"
confy = "0.5.1"
serde = { version = "1.0.151", features = ["derive"] }
